### ISSUE TITLE
Error when creating FlashDevelop project

### ISSUE THREAD

**Issue by Zeon8** [asheigithub/apple-juice-actionscript#5]
Hello, I tried to create a project and got an error:
```
now compiling
????????????/[\x00-\x1F]/
    com/adobe/serialization/json/JSONTokenizer.as

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at ASCompiler.compiler.builds.ExpressionBuilder.getRightValue(CompileEnv env, AS3DataStackElement data, Token matchtoken, Builder builder, Boolean addtryreadproperty)
   at ASCompiler.compiler.ExpressionEval.Eval(AS3Expression expression, Builder importBuilder)
   at ASCompiler.compiler.Builder.build_srcFiles(List`1 tobuildfiles, Boolean isbuildvector, RunTimeDataType vectortype)
   at ASCompiler.compiler.Builder.Build(AS3Proj proj, IList`1 extfunctions)
   at LinkCodeGenCLI.Program.Main(String[] args)
```
Version: v0.97f7

**Comment by asheigithub** [comment]
Have you solved this problem?
This may be a problem with the file encoding
